pipeline:
  deploy:
    image: plugins/ssh
    host: nansen.online.ntnu.no
    user: root
    environment:
      - REGME_CLIENT_ID: ${REGME_CLIENT_ID}
      - REGME_CLIENT_SECRET: ${REGME_CLIENT_SECRET}
    port: 22
    when:
      event: push
      branch: master
    script:
      - cd /srv/www/regme
      - git pull
      - npm install
      - echo 'export const BASE = "https://online.ntnu.no/"' > common/constants2.js
      - echo 'export const API_BASE = "https://online.ntnu.no/api/v1/"' >> common/constants2.js
      - echo 'export const API_EVENTS = "events/"' >> common/constants2.js
      - echo 'export const API_AUTH = "auth/"' >> common/constants2.js
      - echo 'export const API_ATTENDEES = "attendees/"' >> common/constants2.js
      - echo 'export const API_ATTEND = "attend/"' >> common/constants2.js
      - echo 'export const API_USERS = "users/"' >> common/constants2.js
      - echo 'export const CLIENT_SECRET = "${REGME_CLIENT_SECRET}"' >> common/constants2.js
      - echo 'export const CLIENT_ID = "$REGME_CLIENT_ID"' >> common/constants2.js
      - echo 'export const CLIENT_ID = "$$REGME_CLIENT_ID"' >> common/constants2.js
      - echo 'export const CLIENT_ID = "$${REGME_CLIENT_ID}"' >> common/constants2.js
      - echo 'export const CLIENT_ID = "{REGME_CLIENT_ID}"' >> common/constants2.js
      - node /srv/www/regme/node_modules/webpack/bin/webpack.js
